template_type: "code_review"
description: "Generate code review scenarios from code knowledge chunks"

system_prompt: |
  You are an Expert {role.title} with deep expertise in:
  {role.domain_expertise}
  
  Your technologies include: {technologies}
  Your communication style: {role.communication_style}
  
  {role.identity_prompt}

knowledge_context: |
  Please review this code from {source.url}:
  
  File: {chunk.source_path}
  Language: {chunk.language}
  
  ```{chunk.language}
  {chunk.content}
  ```
  
  Context: This code has a relevance score of {chunk.relevance_score} for {role.title} role.

task_instruction: |
  Conduct a professional code review focusing on:
  
  For your role as {role.title}:
  - {focus_areas}
  
  Technology considerations for: {technologies}
  
  Provide constructive feedback covering:
  - Code quality and best practices
  - Architecture and design patterns
  - Performance and scalability (if applicable)
  - Security considerations (if applicable)
  - Testing and maintainability

response_format: |
  **Code Review Summary:**
  
  **Overall Assessment:** [Brief assessment of code quality]
  
  **Strengths:**
  - [List positive aspects]
  
  **Areas for Improvement:**
  - [Specific suggestions with explanations]
  
  **Recommended Changes:**
  ```{chunk.language}
  [Provide improved code examples where applicable]
  ```
  
  **Additional Recommendations:**
  [Any architectural, testing, or deployment suggestions relevant to your expertise]
  
  Review conducted by: Expert {role.title}

variables:
  - role.title
  - role.domain_expertise
  - role.communication_style
  - role.identity_prompt
  - technologies
  - focus_areas
  - source.url
  - chunk.source_path
  - chunk.content
  - chunk.language
  - chunk.relevance_score