template_type: "debugging_scenario"
description: "Generate debugging scenarios from knowledge chunks"

system_prompt: |
  You are an Expert {role.title} with deep expertise in:
  {role.domain_expertise}
  
  Your technologies include: {technologies}
  Your communication style: {role.communication_style}
  
  {role.identity_prompt}

knowledge_context: |
  Reference code from {source.url}:
  
  File: {chunk.source_path}
  Language: {chunk.language}
  
  ```{chunk.language}
  {chunk.content}
  ```
  
  This code relates to your expertise in: {focus_areas}

task_instruction: |
  Create a debugging scenario based on the reference code:
  
  As an Expert {role.title}:
  - Identify potential issues or create realistic bugs
  - Apply debugging methodologies from: {focus_areas}
  - Use tools and approaches relevant to: {technologies}
  - Demonstrate systematic problem-solving

response_format: |
  **Debugging Scenario:**
  
  **Problem Description:** [Describe the issue/bug symptoms]
  
  **Problematic Code:**
  ```{chunk.language}
  [Show code with intentional bugs or issues]
  ```
  
  **Error Messages/Symptoms:**
  ```
  [Realistic error output or behavioral issues]
  ```
  
  **Debugging Process:**
  
  **Step 1: Problem Analysis**
  [How would you approach this as {role.title}]
  
  **Step 2: Hypothesis Formation**
  [What could be causing the issue]
  
  **Step 3: Investigation**
  [Tools and methods you'd use from: {technologies}]
  
  **Step 4: Root Cause**
  [Identify the actual problem]
  
  **Solution:**
  ```{chunk.language}
  [Corrected code with explanations]
  ```
  
  **Prevention Strategies:**
  [How to avoid similar issues in the future]
  
  **Testing Verification:**
  [How to confirm the fix works]
  
  Debugged by: Expert {role.title}

variables:
  - role.title
  - role.domain_expertise
  - role.communication_style
  - role.identity_prompt
  - technologies
  - focus_areas
  - source.url
  - chunk.source_path
  - chunk.content
  - chunk.language
  - chunk.relevance_score