#!/bin/bash
"""
BigAcademy CLI Helper Script
Quick commands for common BigAcademy + Argilla workflows
"""

echo "🎓 BigAcademy CLI Environment"
echo "=============================="
echo ""
echo "📍 Available Commands:"
echo ""
echo "🔧 BigAcademy Core:"
echo "   - Generate datasets: python -m bigacademy.generators.dataset_generator"
echo "   - Run tests: python test_dataset_generator.py"
echo "   - Visualize graph: python visualize_graph.py"
echo ""
echo "🌐 Argilla Integration:"
echo "   - Upload to Argilla: python scripts/upload_to_argilla.py <dataset.jsonl>"
echo "   - Download from Argilla: python scripts/download_from_argilla.py <dataset_name>"
echo ""
echo "📊 Quick Start Workflow:"
echo "   1. cd /app"
echo "   2. python test_dataset_generator.py  # Generate test datasets"
echo "   3. python scripts/upload_to_argilla.py datasets/solution_architect_*.jsonl"
echo "   4. Open http://localhost:6900 to review in Argilla UI"
echo "   5. python scripts/download_from_argilla.py solution_architect_* --analyze"
echo ""
echo "🔗 Services:"
echo "   - Argilla UI: http://localhost:6900 (admin/bigacademy123)"
echo "   - Jupyter Lab: http://localhost:8888?token=bigacademy"
echo "   - Elasticsearch: http://localhost:9200"
echo ""
echo "💡 Environment Variables:"
echo "   - ARGILLA_API_URL: $ARGILLA_API_URL"
echo "   - ARGILLA_API_KEY: $ARGILLA_API_KEY"
echo "   - ARGILLA_WORKSPACE: $ARGILLA_WORKSPACE"
echo ""

# Keep container running
exec "$@"